const temp2=require('mongoose')
const temp12=temp2.Schema({
    name:{
        type:String,
        required:true,
    },
    phoneno:{
        type:String,
        required:true,
    },
    checkin:{
        type:Date,
        required:true,
    },
    custid:{
        type:temp2.Schema.Types.ObjectId,
        ref:'user',
        required:true,
    },
    checkout:{
        type:Date,
        required:true,
    },
    noofguest:{
        type:Number,
        required:true,
    },
    place:{
        type:temp2.Schema.Types.ObjectId,
        ref:'place',
        required:true,
    },
    price:{
        type:Number,
        required:true,
    }
})
module.exports=temp2.model('custinfo',temp12)