const temp2=require('express')
const temp12=temp2.Router()
const multer=require('multer')
const userregister=require('./controllerregister.js')
const userlogin=require('./controllerlogin.js')
const userprofile=require('./controllerprofile.js')
const userlogout=require('./controllerlogout.js')
const userphotolink=require('./controllerphotoadd.js')
const userphotosys=require('./controllerphotosys.js')
const userlistplace=require('./controllergiveplace.js')
const userplacesave=require('./controllerplace.js')
const userplacespeci=require('./controllergiveplacespeci.js')
const userplaceupdate=require('./controllerupdateplace.js')
const userallplace=require('./controllerallplace.js')
const singlepage=require('./controllergiveoneplace.js')
const custin=require('./controllercustin.js')
const bookin=require('./controllercustbook.js')
//temp12.post('/register',function(req,res){
//    console.log('user is')
//    res.send('hi')
//    }
//)
temp12.post('/register',userregister)
temp12.post('/login',userlogin)
temp12.get('/profile',userprofile)
temp12.post('/logout',userlogout)
temp12.post('/upload-by-link',userphotolink)
temp12.post('/listplace',userplacesave)
const photomiddleware=multer({dest:'upload/'})
temp12.post('/upload',photomiddleware.array('photo',100),userphotosys)
temp12.get('/place',userlistplace)
temp12.get('/place/:id',userplacespeci)
temp12.put('/update',userplaceupdate)
temp12.get('/allplace',userallplace)
temp12.get('/specipage/:id',singlepage)
temp12.post('/custin',custin)
temp12.get('/bookin',bookin)
module.exports=temp12